# Generated by Django 4.2.30 on 2026-05-25 04:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('day_number', models.IntegerField(default=1)),
                ('total_miles', models.FloatField(default=0)),
                ('total_driving_hours', models.FloatField(default=0)),
                ('total_on_duty_hours', models.FloatField(default=0)),
                ('total_sleeper_hours', models.FloatField(default=0)),
                ('total_off_duty_hours', models.FloatField(default=0)),
                ('carrier_name', models.CharField(default='', max_length=200)),
                ('main_office_address', models.CharField(default='', max_length=500)),
                ('truck_number', models.CharField(default='', max_length=50)),
                ('trailer_number', models.CharField(default='', max_length=50)),
                ('driver_name', models.CharField(default='', max_length=200)),
                ('shipping_doc', models.CharField(blank=True, default='', max_length=200)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['day_number'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('driver_name', models.CharField(default='Driver', max_length=200)),
                ('carrier_name', models.CharField(default='', max_length=200)),
                ('main_office_address', models.CharField(default='', max_length=500)),
                ('truck_number', models.CharField(default='', max_length=50)),
                ('trailer_number', models.CharField(default='', max_length=50)),
                ('shipping_doc_number', models.CharField(blank=True, default='', max_length=100)),
                ('current_location', models.CharField(max_length=500)),
                ('current_lat', models.FloatField(default=0)),
                ('current_lng', models.FloatField(default=0)),
                ('pickup_location', models.CharField(max_length=500)),
                ('pickup_lat', models.FloatField(default=0)),
                ('pickup_lng', models.FloatField(default=0)),
                ('dropoff_location', models.CharField(max_length=500)),
                ('dropoff_lat', models.FloatField(default=0)),
                ('dropoff_lng', models.FloatField(default=0)),
                ('current_cycle_used', models.FloatField(default=0, help_text='Hours already used in 70-hr/8-day cycle')),
                ('total_distance_miles', models.FloatField(default=0)),
                ('estimated_duration_hours', models.FloatField(default=0)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('active', 'Active'), ('completed', 'Completed')], default='planning', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TripStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_type', models.CharField(choices=[('start', 'Trip Start'), ('pickup', 'Pickup'), ('dropoff', 'Dropoff'), ('fuel', 'Fueling'), ('rest', 'Mandatory Rest'), ('break', '30-min Break'), ('end', 'Trip End')], max_length=20)),
                ('location_name', models.CharField(max_length=500)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('arrival_time', models.DateTimeField()),
                ('departure_time', models.DateTimeField(blank=True, null=True)),
                ('duration_hours', models.FloatField(default=0)),
                ('miles_from_start', models.FloatField(default=0)),
                ('sequence', models.IntegerField(default=0)),
                ('remarks', models.TextField(blank=True, default='')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='trips.trip')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OFF', 'Off Duty'), ('SB', 'Sleeper Berth'), ('D', 'Driving'), ('ON', 'On Duty (Not Driving)')], max_length=3)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration_hours', models.FloatField()),
                ('location', models.CharField(default='', max_length=500)),
                ('remarks', models.CharField(blank=True, default='', max_length=500)),
                ('sequence', models.IntegerField(default=0)),
                ('daily_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='trips.dailylog')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier_name', models.CharField(default='', max_length=200)),
                ('main_office_address', models.CharField(default='', max_length=500)),
                ('truck_number', models.CharField(default='', max_length=50)),
                ('trailer_number', models.CharField(default='', max_length=50)),
                ('home_terminal_timezone', models.CharField(default='US/Eastern', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='dailylog',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='trips.trip'),
        ),
        migrations.AlterUniqueTogether(
            name='dailylog',
            unique_together={('trip', 'date')},
        ),
    ]
